export default {
  crmPrefix: '/aicc-api',
  sdmMessagePrefix: '/aicc-sdm-messageproxy',
  sdmMonkeyPrefix: '/aicc-sdm-monkey',
  sdmCowdialogPrefix: '/aicc-sdm-cowdialog',
  smartAssistPrefix: '/aicc-sra-smartassist',
  imPrefix: '/aicc-scb-improxy',
  talkBotPrefix: '/aicp-talking-bot',
  asrhelper: '/aicp-asr-helper',
  asradapterPrefix: '/aicc-shm-asradapter',
  agentPrefix: '/aicc-shm-smartseat',
  resourcePrefix: '/minio',
  modelPrefix: '/model-test-api',
  gptPrefix: '/aicc-gptproxy',
  workflowPrefix: '/aicc-smartflow',
  excelMaxSize: 5,
  fileMaxSize: 20,
} as const;
