export interface EmojiItem {
  cn: string;
  id: number;
  code: string;
  style: string;
  us: string;
  web_code: string;
  position: Array<number>;
  emoji?: string;
}

// emoji客户端字符数据源  id -表情编号(用来表情面板关联)  cn-[中文]  hk-[繁体]  us-[英文] code-/:*  web_code-/中文
export const emojiData = [
  {
    id: 0,
    cn: '[微笑]',
    hk: '[微笑]',
    us: '[Smile]',
    code: '/::)',
    web_code: '/微笑',
    style: 'smiley_0',
    position: [-132, -132],
  },
  {
    id: 1,
    cn: '[撇嘴]',
    hk: '[撇嘴]',
    us: '[Grimace]',
    code: '/::~',
    web_code: '/撇嘴',
    style: 'smiley_1',
    position: [-660, -594],
  },
  {
    id: 2,
    cn: '[色]',
    hk: '[色]',
    us: '[Drool]',
    code: '/::B',
    web_code: '/色',
    style: 'smiley_2',
    position: [-264, -198],
  },
  {
    id: 3,
    cn: '[发呆]',
    hk: '[發呆]',
    us: '[Scowl]',
    code: '/::|',
    web_code: '/发呆',
    style: 'smiley_3',
    position: [-330, -264],
  },
  {
    id: 4,
    cn: '[得意]',
    hk: '[得意]',
    us: '[CoolGuy]',
    code: '/:8-)',
    web_code: '/得意',
    style: 'smiley_4',
    position: [-462, 0],
  },
  {
    id: 5,
    cn: '[流泪]',
    hk: '[流淚]',
    us: '[Sob]',
    code: '/::<',
    web_code: '/流泪',
    style: 'smiley_5',
    position: [-198, -462],
  },
  {
    id: 6,
    cn: '[害羞]',
    hk: '[害羞]',
    us: '[Shy]',
    code: '/::$',
    web_code: '/害羞',
    style: 'smiley_6',
    position: [-528, -198],
  },
  {
    id: 7,
    cn: '[闭嘴]',
    hk: '[閉嘴]',
    us: '[Silent]',
    code: '/::X',
    web_code: '/闭嘴',
    style: 'smiley_7',
    position: [-330, -528],
  },
  {
    id: 8,
    cn: '[睡]',
    hk: '[睡]',
    us: '[Sleep]',
    code: '/::Z',
    web_code: '/睡',
    style: 'smiley_8',
    position: [-594, -198],
  },
  {
    id: 9,
    cn: '[大哭]',
    hk: '[大哭]',
    us: '[Cry]',
    code: '/::"(',
    web_code: '/大哭',
    style: 'smiley_9',
    position: [-132, -594],
  },
  {
    id: 10,
    cn: '[尴尬]',
    hk: '[尷尬]',
    us: '[Awkward]',
    code: '/::-|',
    web_code: '/尴尬',
    style: 'smiley_10',
    position: [-198, -66],
  },
  {
    id: 11,
    cn: '[发怒]',
    hk: '[發怒]',
    us: '[Angry]',
    code: '/::@',
    web_code: '/发怒',
    style: 'smiley_11',
    position: [-198, -132],
  },
  {
    id: 12,
    cn: '[调皮]',
    hk: '[調皮]',
    us: '[Tongue]',
    code: '/::P',
    web_code: '/调皮',
    style: 'smiley_12',
    position: [0, -198],
  },
  {
    id: 13,
    cn: '[呲牙]',
    hk: '[呲牙]',
    us: '[Grin]',
    code: '/::D',
    web_code: '/呲牙',
    style: 'smiley_13',
    position: [-66, -198],
  },
  {
    id: 14,
    cn: '[惊讶]',
    hk: '[驚訝]',
    us: '[Surprise]',
    code: '/::O',
    web_code: '/惊讶',
    style: 'smiley_14',
    position: [-132, -198],
  },
  {
    id: 15,
    cn: '[难过]',
    hk: '[難過]',
    us: '[Frown]',
    code: '/::(',
    web_code: '/难过',
    style: 'smiley_15',
    position: [-198, -198],
  },
  // , { 'id': 16, 'cn': '[酷]', 'hk': '[酷]', 'us': '[Ruthless]', 'code': '/::+', 'web_code': '/酷', 'style': 'smiley_16' }
  {
    id: 17,
    cn: '[冷汗]',
    hk: '[冷汗]',
    us: '[Blush]',
    code: '/:--b',
    web_code: '/冷汗',
    style: 'smiley_17',
    position: [-264, 0],
  },
  {
    id: 18,
    cn: '[抓狂]',
    hk: '[抓狂]',
    us: '[Scream]',
    code: '/::Q',
    web_code: '/抓狂',
    style: 'smiley_18',
    position: [-264, -66],
  },
  {
    id: 19,
    cn: '[吐]',
    hk: '[吐]',
    us: '[Puke]',
    code: '/::T',
    web_code: '/吐',
    style: 'smiley_19',
    position: [-264, -132],
  },
  {
    id: 20,
    cn: '[偷笑]',
    hk: '[偷笑]',
    us: '[Chuckle]',
    code: '/:,@P',
    web_code: '/偷笑',
    style: 'smiley_20',
    position: [0, -264],
  },
  {
    id: 21,
    cn: '[愉快]',
    hk: '[愉快]',
    us: '[Joyful]',
    code: '/:,@-D',
    web_code: '/可爱',
    style: 'smiley_21',
    position: [-66, -264],
  },
  {
    id: 22,
    cn: '[白眼]',
    hk: '[白眼]',
    us: '[Slight]',
    code: '/::d',
    web_code: '/白眼',
    style: 'smiley_22',
    position: [-132, -264],
  },
  {
    id: 23,
    cn: '[傲慢]',
    hk: '[傲慢]',
    us: '[Smug]',
    code: '/:,@o',
    web_code: '/傲慢',
    style: 'smiley_23',
    position: [-198, -264],
  },
  // , { 'id': 24, 'cn': '[饥饿]', 'hk': '[饑餓]', 'us': '[Hungry]', 'code': '/::g', 'web_code': '/饥饿', 'style': 'smiley_24' }
  {
    id: 25,
    cn: '[困]',
    hk: '[累]',
    us: '[Drowsy]',
    code: '/:|-)',
    web_code: '/困',
    style: 'smiley_25',
    position: [-264, -264],
  },
  {
    id: 26,
    cn: '[惊恐]',
    hk: '[驚恐]',
    us: '[Panic]',
    code: '/::!',
    web_code: '/惊恐',
    style: 'smiley_26',
    position: [-330, 0],
  },
  {
    id: 27,
    cn: '[流汗]',
    hk: '[流汗]',
    us: '[Sweat]',
    code: '/::L',
    web_code: '/流汗',
    style: 'smiley_27',
    position: [-330, -66],
  },
  {
    id: 28,
    cn: '[憨笑]',
    hk: '[大笑]',
    us: '[Laugh]',
    code: '/::>',
    web_code: '/憨笑',
    style: 'smiley_28',
    position: [-330, -132],
  },
  {
    id: 29,
    cn: '[悠闲]',
    hk: '[悠閑]',
    us: '[Commando]',
    code: '/::,@',
    web_code: '/大兵',
    style: 'smiley_29',
    position: [-330, -198],
  },
  {
    id: 30,
    cn: '[奋斗]',
    hk: '[奮鬥]',
    us: '[Determined]',
    code: '/:,@f',
    web_code: '/奋斗',
    style: 'smiley_30',
    position: [0, -330],
  },
  {
    id: 31,
    cn: '[咒骂]',
    hk: '[咒罵]',
    us: '[Scold]',
    code: '/::-S',
    web_code: '/咒骂',
    style: 'smiley_31',
    position: [-66, -330],
  },
  {
    id: 32,
    cn: '[疑问]',
    hk: '[疑問]',
    us: '[Shocked]',
    code: '/:?',
    web_code: '/疑问',
    style: 'smiley_32',
    position: [-396, -198],
  },
  {
    id: 33,
    cn: '[嘘]',
    hk: '[噓]',
    us: '[Shhh]',
    code: '/:,@x',
    web_code: '/嘘',
    style: 'smiley_33',
    position: [-66, -396],
  },
  {
    id: 34,
    cn: '[晕]',
    hk: '[暈]',
    us: '[Dizzy]',
    code: '/:,@@',
    web_code: '/晕',
    style: 'smiley_34',
    position: [-132, -396],
  },
  // , { 'id': 35, 'cn': '[疯了]', 'hk': '[瘋了]', 'us': '[Tormented]', 'code': '/::8', 'web_code': '/折磨', 'style': 'smiley_35' }
  {
    id: 36,
    cn: '[衰]',
    hk: '[衰]',
    us: '[Toasted]',
    code: '/:,@!',
    web_code: '/衰',
    style: 'smiley_36',
    position: [-198, -396],
  },
  {
    id: 37,
    cn: '[骷髅]',
    hk: '[骷髏頭]',
    us: '[Skull]',
    code: '/:!!!',
    web_code: '/骷髅',
    style: 'smiley_37',
    position: [-264, -396],
  },
  {
    id: 38,
    cn: '[敲打]',
    hk: '[敲打]',
    us: '[Hammer]',
    code: '/:xx',
    web_code: '/敲打',
    style: 'smiley_38',
    position: [-330, -396],
  },
  {
    id: 39,
    cn: '[再见]',
    hk: '[再見]',
    us: '[Wave]',
    code: '/:bye',
    web_code: '/再见',
    style: 'smiley_39',
    position: [-396, -396],
  },
  {
    id: 40,
    cn: '[擦汗]',
    hk: '[擦汗]',
    us: '[Speechless]',
    code: '/:wipe',
    web_code: '/擦汗',
    style: 'smiley_40',
    position: [-462, -66],
  },
  {
    id: 41,
    cn: '[抠鼻]',
    hk: '[摳鼻]',
    us: '[NosePick]',
    code: '/:dig',
    web_code: '/抠鼻',
    style: 'smiley_41',
    position: [-462, -132],
  },
  {
    id: 42,
    cn: '[鼓掌]',
    hk: '[鼓掌]',
    us: '[Clap]',
    code: '/:handclap',
    web_code: '/鼓掌',
    style: 'smiley_42',
    position: [-462, -198],
  },
  // , { 'id': 43, 'cn': '[糗大了]', 'hk': '[羞辱]', 'us': '[Shame]', 'code': '/:&-(', 'web_code': '/糗大了', 'style': 'smiley_43' }
  {
    id: 44,
    cn: '[坏笑]',
    hk: '[壞笑]',
    us: '[Trick]',
    code: '/:B-)',
    web_code: '/坏笑',
    style: 'smiley_44',
    position: [-462, -264],
  },
  {
    id: 45,
    cn: '[左哼哼]',
    hk: '[左哼哼]',
    us: '[Bah！L]',
    code: '/:<@',
    web_code: '/左哼哼',
    style: 'smiley_45',
    position: [-462, -330],
  },
  {
    id: 46,
    cn: '[右哼哼]',
    hk: '[右哼哼]',
    us: '[Bah！R]',
    code: '/:@>',
    web_code: '/右哼哼',
    style: 'smiley_46',
    position: [0, 0],
  },
  {
    id: 47,
    cn: '[哈欠]',
    hk: '[哈欠]',
    us: '[Yawn]',
    code: '/::-O',
    web_code: '/哈欠',
    style: 'smiley_47',
    position: [-0, -462],
  },
  {
    id: 48,
    cn: '[鄙视]',
    hk: '[鄙視]',
    us: '[Pooh-pooh]',
    code: '/:>-|',
    web_code: '/鄙视',
    style: 'smiley_48',
    position: [-66, -462],
  },
  {
    id: 49,
    cn: '[委屈]',
    hk: '[委屈]',
    us: '[Shrunken]',
    code: '/:P-(',
    web_code: '/委屈',
    style: 'smiley_49',
    position: [-132, -462],
  },
  {
    id: 50,
    cn: '[快哭了]',
    hk: '[快哭了]',
    us: '[TearingUp]',
    code: '/::"|',
    web_code: '/快哭了',
    style: 'smiley_50',
    position: [-264, -462],
  },
  {
    id: 51,
    cn: '[阴险]',
    hk: '[陰險]',
    us: '[Sly]',
    code: '/:X-)',
    web_code: '/阴险',
    style: 'smiley_51',
    position: [-330, -462],
  },
  {
    id: 52,
    cn: '[亲亲]',
    hk: '[親親]',
    us: '[Kiss]',
    code: '/::*',
    web_code: '/亲亲',
    style: 'smiley_52',
    position: [-396, -462],
  },
  // , { 'id': 53, 'cn': '[吓]', 'hk': '[嚇]', 'us': '[Wrath]', 'code': '/:@x', 'web_code': '/吓', 'style': 'smiley_53' }
  {
    id: 54,
    cn: '[可怜]',
    hk: '[可憐]',
    us: '[Whimper]',
    code: '/:8*',
    web_code: '/可怜',
    style: 'smiley_54',
    position: [-462, -462],
  },
  {
    id: 55,
    cn: '[菜刀]',
    hk: '[菜刀]',
    us: '[Cleaver]',
    code: '/:pd',
    web_code: '/菜刀',
    style: 'smiley_55',
    position: [-528, 0],
  },
  {
    id: 56,
    cn: '[西瓜]',
    hk: '[西瓜]',
    us: '[Watermelon]',
    code: '/:<W>',
    web_code: '/西瓜',
    style: 'smiley_56',
    position: [-528, -66],
  },
  {
    id: 57,
    cn: '[啤酒]',
    hk: '[啤酒]',
    us: '[Beer]',
    code: '/:beer',
    web_code: '/啤酒',
    style: 'smiley_57',
    position: [-528, -132],
  },
  // , { 'id': 58, 'cn': '[篮球]', 'hk': '[籃球]', 'us': '[Basketball]', 'code': '/:basketb', 'web_code': '/篮球', 'style': 'smiley_58' }
  // , { 'id': 59, 'cn': '[乒乓]', 'hk': '[乒乓]', 'us': '[PingPong]', 'code': '/:oo', 'web_code': '/乒乓', 'style': 'smiley_59' }
  {
    id: 60,
    cn: '[咖啡]',
    hk: '[咖啡]',
    us: '[Coffee]',
    code: '/:coffee',
    web_code: '/咖啡',
    style: 'smiley_60',
    position: [-528, -264],
  },
  {
    id: 61,
    cn: '[饭]',
    hk: '[飯]',
    us: '[Rice]',
    code: '/:eat',
    web_code: '/饭',
    style: 'smiley_61',
    position: [-528, -330],
  },
  {
    id: 62,
    cn: '[猪头]',
    hk: '[豬頭]',
    us: '[Pig]',
    code: '/:pig',
    web_code: '/猪头',
    style: 'smiley_62',
    position: [-528, -396],
  },
  {
    id: 63,
    cn: '[玫瑰]',
    hk: '[玫瑰]',
    us: '[Rose]',
    code: '/:rose',
    web_code: '/玫瑰',
    style: 'smiley_63',
    position: [-528, -462],
  },
  {
    id: 64,
    cn: '[凋谢]',
    hk: '[枯萎]',
    us: '[Wilt]',
    code: '/:fade',
    web_code: '/凋谢',
    style: 'smiley_64',
    position: [0, -528],
  },
  {
    id: 65,
    cn: '[嘴唇]',
    hk: '[嘴唇]',
    us: '[Lips]',
    code: '/:showlove',
    web_code: '/示爱',
    style: 'smiley_65',
    position: [-66, -528],
  },
  {
    id: 66,
    cn: '[爱心]',
    hk: '[愛心]',
    us: '[Heart]',
    code: '/:heart',
    web_code: '/爱心',
    style: 'smiley_66',
    position: [-132, -528],
  },
  {
    id: 67,
    cn: '[心碎]',
    hk: '[心碎]',
    us: '[BrokenHeart]',
    code: '/:break',
    web_code: '/心碎',
    style: 'smiley_67',
    position: [-198, -528],
  },
  {
    id: 68,
    cn: '[蛋糕]',
    hk: '[蛋糕]',
    us: '[Cake]',
    code: '/:cake',
    web_code: '/蛋糕',
    style: 'smiley_68',
    position: [-264, -528],
  },
  // , { 'id': 69, 'cn': '[闪电]', 'hk': '[閃電]', 'us': '[Lightning]', 'code': '/:li', 'web_code': '/闪电', 'style': 'smiley_69' }
  {
    id: 70,
    cn: '[炸弹]',
    hk: '[炸彈]',
    us: '[Bomb]',
    code: '/:bome',
    web_code: '/炸弹',
    style: 'smiley_70',
    position: [-396, -528],
  },
  // , { 'id': 71, 'cn': '[刀]', 'hk': '[刀]', 'us': '[Dagger]', 'code': '/:kn', 'web_code': '/刀', 'style': 'smiley_71' }
  // , { 'id': 72, 'cn': '[足球]', 'hk': '[足球]', 'us': '[Soccer]', 'code': '/:footb', 'web_code': '/足球', 'style': 'smiley_72' }
  // , { 'id': 73, 'cn': '[瓢虫]', 'hk': '[甲蟲]', 'us': '[Ladybug]', 'code': '/:ladybug', 'web_code': '/瓢虫', 'style': 'smiley_73' }
  {
    id: 74,
    cn: '[便便]',
    hk: '[便便]',
    us: '[Poop]',
    code: '/:shit',
    web_code: '/便便',
    style: 'smiley_74',
    position: [-462, -528],
  },
  {
    id: 75,
    cn: '[月亮]',
    hk: '[月亮]',
    us: '[Moon]',
    code: '/:moon',
    web_code: '/月亮',
    style: 'smiley_75',
    position: [-528, -528],
  },
  {
    id: 76,
    cn: '[太阳]',
    hk: '[太陽]',
    us: '[Sun]',
    code: '/:sun',
    web_code: '/太阳',
    style: 'smiley_76',
    position: [-594, 0],
  },
  // , { 'id': 77, 'cn': '[礼物]', 'hk': '[禮物]', 'us': '[Gift]', 'code': '/:gift', 'web_code': '/礼物', 'style': 'smiley_77' }
  {
    id: 78,
    cn: '[拥抱]',
    hk: '[擁抱]',
    us: '[Hug]',
    code: '/:hug',
    web_code: '/拥抱',
    style: 'smiley_78',
    position: [-594, -66],
  },
  {
    id: 79,
    cn: '[强]',
    hk: '[強]',
    us: '[ThumbsUp]',
    code: '/:strong',
    web_code: '/强',
    style: 'smiley_79',
    position: [-594, -132],
  },
  {
    id: 80,
    cn: '[弱]',
    hk: '[弱]',
    us: '[ThumbsDown]',
    code: '/:weak',
    web_code: '/弱',
    style: 'smiley_80',
    position: [-594, -264],
  },
  {
    id: 81,
    cn: '[握手]',
    hk: '[握手]',
    us: '[Shake]',
    code: '/:share',
    web_code: '/握手',
    style: 'smiley_81',
    position: [-594, -330],
  },
  {
    id: 82,
    cn: '[胜利]',
    hk: '[勝利]',
    us: '[Peace]',
    code: '/:v',
    web_code: '/胜利',
    style: 'smiley_82',
    position: [-594, -396],
  },
  {
    id: 83,
    cn: '[抱拳]',
    hk: '[抱拳]',
    us: '[Fight]',
    code: '/:@)',
    web_code: '/抱拳',
    style: 'smiley_83',
    position: [-594, -462],
  },
  {
    id: 84,
    cn: '[勾引]',
    hk: '[勾引]',
    us: '[Beckon]',
    code: '/:jj',
    web_code: '/勾引',
    style: 'smiley_84',
    position: [-594, -528],
  },
  {
    id: 85,
    cn: '[拳头]',
    hk: '[拳頭]',
    us: '[Fist]',
    code: '/:@@',
    web_code: '/拳头',
    style: 'smiley_85',
    position: [0, -594],
  },
  // , { 'id': 86, 'cn': '[差劲]', 'hk': '[差勁]', 'us': '[Pinky]', 'code': '/:bad', 'web_code': '/差劲', 'style': 'smiley_86' }
  // , { 'id': 87, 'cn': '[爱你]', 'hk': '[愛你]', 'us': '[RockOn]', 'code': '/:lvu', 'web_code': '/爱你', 'style': 'smiley_87' }
  // , { 'id': 88, 'cn': '[NO]', 'hk': '[NO]', 'us': '[Nuh-uh]', 'code': '/:no', 'web_code': '/NO', 'style': 'smiley_88' }
  {
    id: 89,
    cn: '[OK]',
    hk: '[OK]',
    us: '[OK]',
    code: '/:ok',
    web_code: '/OK',
    style: 'smiley_89',
    position: [-66, -594],
  },
  // , { 'id': 90, 'cn': '[爱情]', 'hk': '[愛情]', 'us': '[InLove]', 'code': '/:love', 'web_code': '/爱情', 'style': 'smiley_90' }
  // , { 'id': 91, 'cn': '[飞吻]', 'hk': '[飛吻]', 'us': '[Blowkiss]', 'code': '/:<L>', 'web_code': '/飞吻', 'style': 'smiley_91' }
  {
    id: 92,
    cn: '[跳跳]',
    hk: '[跳跳]',
    us: '[Waddle]',
    code: '/:jump',
    web_code: '/跳跳',
    style: 'smiley_92',
    position: [-198, -594],
  },
  {
    id: 93,
    cn: '[发抖]',
    hk: '[發抖]',
    us: '[Tremble]',
    code: '/:shake',
    web_code: '/发抖',
    style: 'smiley_93',
    position: [-264, -594],
  },
  {
    id: 94,
    cn: '[怄火]',
    hk: '[噴火]',
    us: '[Aaagh!]',
    code: '/:<O>',
    web_code: '/怄火',
    style: 'smiley_94',
    position: [-330, -594],
  },
  {
    id: 95,
    cn: '[转圈]',
    hk: '[轉圈]',
    us: '[Twirl]',
    code: '/:circle',
    web_code: '/转圈',
    style: 'smiley_95',
    position: [-396, -594],
  },
  // , { 'id': 96, 'cn': '[磕头]', 'hk': '[磕頭]', 'us': '[Kotow]', 'code': '/:kotow', 'web_code': '/磕头', 'style': 'smiley_96' }
  // , { 'id': 97, 'cn': '[回头]', 'hk': '[回頭]', 'us': '[Dramatic]', 'code': '/:turn', 'web_code': '/回头', 'style': 'smiley_97' }
  // , { 'id': 98, 'cn': '[跳绳]', 'hk': '[跳繩]', 'us': '[JumpRope]', 'code': '/:skip', 'web_code': '/跳绳', 'style': 'smiley_98' }
  // , { 'id': 99, 'cn': '[投降]', 'hk': '[投降]', 'us': '[Surrender]', 'code': '/:oY', 'web_code': '/挥手', 'style': 'smiley_99' }
  // , { 'id': 100, 'cn': '[激动]', 'hk': '[激動]', 'us': '[Hooray]', 'code': '/:#-0', 'web_code': '/激动', 'style': 'smiley_100' }
  // , { 'id': 101, 'cn': '[乱舞]', 'hk': '[亂舞]', 'us': '[Meditate]', 'code': '/:hiphot', 'web_code': '/街舞', 'style': 'smiley_101' }
  // , { 'id': 102, 'cn': '[献吻]', 'hk': '[獻吻]', 'us': '[Smooch]', 'code': '/:kiss', 'web_code': '/献吻', 'style': 'smiley_102' }
  // , { 'id': 103, 'cn': '[左太极]', 'hk': '[左太極]', 'us': '[TaiChi L]', 'code': '/:<&', 'web_code': '/左太极', 'style': 'smiley_103' }
  // , { 'id': 104, 'cn': '[右太极]', 'hk': '[右太極]', 'us': '[TaiChi R]', 'code': '/:&>', 'web_code': '/右太极', 'style': 'smiley_104' }
  {
    id: 204,
    cn: '[嘿哈]',
    hk: '[吼嘿]',
    us: '[Hey]',
    code: '',
    web_code: '',
    style: 'e2_04',
    position: [-462, -396],
  },
  {
    id: 205,
    cn: '[捂脸]',
    hk: '[掩面]',
    us: '[Facepalm]',
    code: '',
    web_code: '',
    style: 'e2_05',
    position: [0, -66],
  },
  {
    id: 202,
    cn: '[奸笑]',
    hk: '[奸笑]',
    us: '[Smirk]',
    code: '',
    web_code: '',
    style: 'e2_02',
    position: [-66, 0],
  },
  {
    id: 206,
    cn: '[机智]',
    hk: '[機智]',
    us: '[Smart]',
    code: '',
    web_code: '',
    style: 'e2_06',
    position: [-66, -66],
  },
  {
    id: 212,
    cn: '[皱眉]',
    hk: '[皺眉]',
    us: '[Moue]',
    code: '',
    web_code: '',
    style: 'e2_12',
    position: [0, -132],
  },
  {
    id: 211,
    cn: '[耶]',
    hk: '[歐耶]',
    us: '[Yeah!]',
    code: '',
    web_code: '',
    style: 'e2_11',
    position: [-132, -66],
  },
  // , { 'id': 207, 'cn': '[茶]', 'hk': '[茶]', 'us': '[Tea]', 'code': '', 'web_code': '', 'style': 'e2_07' }
  {
    id: 209,
    cn: '[红包]',
    hk: '[Packet]',
    us: '[Packet]',
    code: '',
    web_code: '',
    style: 'e2_09',
    position: [-132, 0],
  },
  // , { 'id': 210, 'cn': '[蜡烛]', 'hk': '[蠟燭]', 'us': '[Candle]', 'code': '', 'web_code': '', 'style': 'e2_10' }
  // , { 'id': 215, 'cn': '[福]', 'hk': '[福]', 'us': '[Blessing]', 'code': '', 'web_code': '', 'style': 'e2_15' }
  {
    id: 214,
    cn: '[鸡]',
    hk: '[小雞]',
    us: '[Chick]',
    code: '',
    web_code: '',
    style: 'e2_14',
    position: [-66, -132],
  },
  {
    id: 300,
    cn: '[笑脸]',
    emoji: '😄',
    hk: '',
    us: '',
    code: '\\ue415',
    web_code: '',
    style: 'u1F604',
    position: [-660, -132],
  },
  {
    id: 301,
    cn: '[生病]',
    emoji: '😷',
    hk: '',
    us: '',
    code: '\\ue40c',
    web_code: '',
    style: 'u1F637',
    position: [-198, 0],
  },
  {
    id: 302,
    cn: '[破涕为笑]',
    emoji: '😂',
    hk: '',
    us: '',
    code: '\\ue412',
    web_code: '',
    style: 'u1F602',
    position: [-660, -66],
  },
  {
    id: 303,
    cn: '[吐舌]',
    emoji: '😝',
    hk: '',
    us: '',
    code: '\\ue409',
    web_code: '',
    style: 'u1F61D',
    position: [-660, -330],
  },
  {
    id: 304,
    cn: '[脸红]',
    emoji: '😳',
    hk: '',
    us: '',
    code: '\\ue40d',
    web_code: '',
    style: 'u1F633',
    position: [-660, -462],
  },
  {
    id: 305,
    cn: '[恐惧]',
    emoji: '😱',
    hk: '',
    us: '',
    code: '\\ue107',
    web_code: '',
    style: 'u1F631',
    position: [-660, -396],
  },
  {
    id: 306,
    cn: '[失望]',
    emoji: '😔',
    hk: '',
    us: '',
    code: '\\ue403',
    web_code: '',
    style: 'u1F614',
    position: [-660, -264],
  },
  {
    id: 307,
    cn: '[无语]',
    emoji: '😒',
    hk: '',
    us: '',
    code: '\\ue40e',
    web_code: '',
    style: 'u1F612',
    position: [-660, -198],
  },
  {
    id: 308,
    cn: '[鬼魂]',
    emoji: '👻',
    hk: '',
    us: '',
    code: '\\ue11b',
    web_code: '',
    style: 'u1F47B',
    position: [-594, -594],
  },
  {
    id: 309,
    cn: '[合十]',
    emoji: '🙏',
    hk: '',
    us: '',
    code: '\\ue41d',
    web_code: '',
    style: 'u1F64F',
    position: [-660, -528],
  },
  {
    id: 310,
    cn: '[强壮]',
    emoji: '💪',
    hk: '',
    us: '',
    code: '\\ue14c',
    web_code: '',
    style: 'u1F4AA',
    position: [-660, 0],
  },
  {
    id: 311,
    cn: '[庆祝]',
    emoji: '🎉',
    hk: '',
    us: '',
    code: '\\ue312',
    web_code: '',
    style: 'u1F389',
    position: [-528, -594],
  },
  {
    id: 312,
    cn: '[礼物]',
    hk: '',
    us: '',
    code: '\\ue112',
    web_code: '',
    style: 'u1F381',
    position: [-462, -594],
  },
  {
    id: 313,
    cn: '[吃瓜]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_313',
    position: [-132, -330],
  },
  {
    id: 314,
    cn: '[加油]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_314',
    position: [-198, -330],
  },
  {
    id: 315,
    cn: '[汗]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_315',
    position: [-264, -330],
  },
  {
    id: 316,
    cn: '[天啊]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_316',
    position: [-330, -330],
  },
  {
    id: 317,
    cn: '[Emm]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_317',
    position: [-396, 0],
  },
  {
    id: 318,
    cn: '[社会社会]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_318',
    position: [-396, -66],
  },
  {
    id: 319,
    cn: '[旺柴]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_319',
    position: [-396, -132],
  },
  {
    id: 320,
    cn: '[好的]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_320',
    position: [-396, -264],
  },
  {
    id: 321,
    cn: '[打脸]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_321',
    position: [-396, -330],
  },
  {
    id: 322,
    cn: '[哇]',
    hk: '[]',
    us: '[]',
    code: '',
    web_code: '',
    style: 'smiley_322',
    position: [0, -396],
  },
];

export const emotionMap = (() => {
  const map: { [K in string]: EmojiItem } = {};
  emojiData.forEach((item) => {
    map[item.cn] = item;
  });
  return map;
})();

/**
 * 将表情转换成对应表情编码
 * @param html
 * @returns
 */
export function transToText(html: string): string {
  const imgReg = /<img.*?(?:>|\/>)/gi;
  html = html.replace(imgReg, (match) => {
    const srcReg = /title=[\'\"]?([^\'\"]*)[\'\"]?/i;
    const title = match.match(srcReg);
    return (title && title[1]) || match;
  });
  return html;
}

/**
 * 将表情编码转换成img标签
 * @param name 表情编码
 * @returns
 */
export function transToImage(name: string): HTMLImageElement {
  const item = emotionMap[name];
  const img = document.createElement('img');
  img.style.setProperty('--positionX', `${item?.position[0] || 0}`);
  img.style.setProperty('--positionY', `${item?.position[1] || 0}`);
  img.className = `qqemoji ${item.style}`;
  img.title = item.cn;
  img.src = require('@aicc/assets/es/v.png');
  return img;
}

/**
 * 将字符串中的表情编码替换成图片
 * @param text
 * @returns
 */
export function transToHtml(text: string): string {
  text = text.replace(/\[(.*?)\]/g, (match) => {
    const item = emotionMap[match];
    if (!item) {
      return match;
    }
    return `<img class="qqemoji ${item.style}" style="--positionX: ${
      item?.position[0] || 0
    }; --positionY: ${
      item?.position[1] || 0
    }" src="${require('@aicc/assets/es/v.png')}" title="${match}" />`;
  });
  return text;
}
