/// <reference path="../typings.d.ts" />

export * from './emoji.png';
export * from './file/audio.svg';
export * from './file/avi.svg';
export * from './file/csv.svg';
export * from './file/doc.svg';
export * from './file/gif.svg';
export * from './file/mp4.svg';
export * from './file/pdf.svg';
export * from './file/txt.svg';
export * from './file/unknow.svg';
export * from './file/wmv.svg';
export * from './file/music.svg';
export * from './file/image.svg';
export * from './file/unknown.svg';
export * from './file/ppt.svg';
export * from './svg/play.svg';
export * from './v.png';
export * from './videoAuth.png';
export * from './audioAuth.png';
export * from './svg/empty.svg';
export * from './image.png';
export * from './micro-icon.png';
